### ISSUE TITLE
Import model

### ISSUE THREAD

**Issue by miltonbsn** [brmodeloweb/brmodelo-app#76]
# Summary

From the web interface users should be able to import a file from their local machine.
This first iteration will allow only import of `.brmw` files.

- #255 
- #297 

# To be defined

- Tag as imported file in models list?

# Output

- [x] Import endpoints 3556f7f
- [x] Import flow designs;
- [ ] Frontend implementation of import flow;
- [ ] Integrate frontend and endpoints;

**Comment by idmarjr** [comment]
We're deprioritizing the development of this feature due to the securities complexity it introduce to BRMW.  
We're working to increase the share capabilities of BRMW and soon, enable users to import models created at BRMW by other users via public URL.

But for now, more integrations with brModelo desktop are out of our plans.
